name: test

on:
  pull_request:
    branches:
      - main
      - test

jobs:
  win-job:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
      - run: docker --version
      # - run: docker --help
      - run: echo "hello world"
